name: gstama_fastasplitter
description: TAMA GO util script: Split fasta file
keywords:
  - fasta
tools:
  - gstama:
      description: Gene-Switch Transcriptome Annotation by Modular Algorithms
      homepage: https://github.com/sguizard/gs-tama
      documentation: https://github.com/sguizard/gs-tama
      tool_dev_url: https://github.com/sguizard/gs-tama
      doi: ""
      licence: ['GPL v3 License']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: fasta file
      pattern: "*.fa"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - fa:
      type: file
      description: splited fasta file
      pattern: "*.fa"

authors:
  - "@sguizard"
